In [24]:
import numpy as np
import pandas as pd

In [27]:
satis1={"Tarih":["01.08.2026","01.08.2026","02.08.2026"],
        "Ürün":["Süt","Ekmek","Kahve"],
        "Kategori":["İçecek","Fırın","İçecek"],
        "Adet":[3,np.nan,2],
        "Birim Fiyat":[45,15,180]
        }

In [28]:
dataFrame1=pd.DataFrame(satis1)
dataFrame1.to_excel("market_verisi.xlsx",index=False)

In [31]:
dataFrame1=pd.read_excel("market_verisi.xlsx")

In [41]:
dataFrame1.head()

        Tarih   Ürün Kategori  Adet  Birim Fiyat
0  01.08.2026    Süt   İçecek   3.0           45
1  01.08.2026  Ekmek    Fırın   NaN           15
2  02.08.2026  Kahve   İçecek   2.0          180

In [45]:
dataFrame1.tail()

        Tarih   Ürün Kategori  Adet  Birim Fiyat
0  01.08.2026    Süt   İçecek   3.0           45
1  01.08.2026  Ekmek    Fırın   NaN           15
2  02.08.2026  Kahve   İçecek   2.0          180

In [46]:
dataFrame1.isnull()

   Tarih   Ürün  Kategori   Adet  Birim Fiyat
0  False  False     False  False        False
1  False  False     False   True        False
2  False  False     False  False        False

In [47]:
dataFrame1.isnull().sum()

Tarih          0
Ürün           0
Kategori       0
Adet           1
Birim Fiyat    0
dtype: int64

In [48]:
dataFrame1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Tarih        3 non-null      str
 1   Ürün         3 non-null      str
 2   Kategori     3 non-null      str
 3   Adet         2 non-null      float64
 4   Birim Fiyat  3 non-null      int64
dtypes: float64(1), int64(1), str(3)
memory usage: 252.0 bytes

In [51]:
dataFrame1.fillna(8,inplace=True)

        Tarih   Ürün Kategori  Adet  Birim Fiyat
0  01.08.2026    Süt   İçecek   3.0           45
1  01.08.2026  Ekmek    Fırın   8.0           15
2  02.08.2026  Kahve   İçecek   2.0          180

In [52]:
dataFrame1

        Tarih   Ürün Kategori  Adet  Birim Fiyat
0  01.08.2026    Süt   İçecek   3.0           45
1  01.08.2026  Ekmek    Fırın   8.0           15
2  02.08.2026  Kahve   İçecek   2.0          180

In [54]:
dataFrame1['Toplam Tutar'] = dataFrame1['Adet'] * dataFrame1['Birim Fiyat']
dataFrame1

        Tarih   Ürün Kategori  Adet  Birim Fiyat  Toplam Tutar
0  01.08.2026    Süt   İçecek   3.0           45         135.0
1  01.08.2026  Ekmek    Fırın   8.0           15         120.0
2  02.08.2026  Kahve   İçecek   2.0          180         360.0

In [58]:

en_cok_satilan_urun = dataFrame1.groupby("Ürün")["Adet"].sum().idxmax()
print(f"En fazla satılan ürün: {en_cok_satilan_urun}")

En fazla satılan ürün: Ekmek

In [59]:
en_cok_gelir_getiren_urun=dataFrame1.groupby("Ürün")["Toplam Tutar"].sum().idxmax()
print(f"En fazla gelir getiren ürün: {en_cok_gelir_getiren_urun}")

En fazla gelir getiren ürün: Kahve

In [65]:
grouped_by_category=dataFrame1.groupby("Kategori")
grouped_by_category.sum()

                         Tarih      Ürün  Adet  Birim Fiyat  Toplam Tutar
Kategori
Fırın               01.08.2026     Ekmek   8.0           15         120.0
İçecek    01.08.202602.08.2026  SütKahve   5.0          225         495.0

In [66]:
grouped_by_category=dataFrame1.groupby("Kategori")["Adet"].sum()
print(grouped_by_category)

Kategori
Fırın     8.0
İçecek    5.0
Name: Adet, dtype: float64

In [67]:
grouped_by_category=dataFrame1.groupby("Kategori")["Toplam Tutar"].sum()
print(grouped_by_category)

Kategori
Fırın     120.0
İçecek    495.0
Name: Toplam Tutar, dtype: float64

In [68]:
grouped_by_category=dataFrame1.groupby("Kategori")["Birim Fiyat"].sum()
print(grouped_by_category)

Kategori
Fırın      15
İçecek    225
Name: Birim Fiyat, dtype: int64

In [74]:
pahali_urunler=dataFrame1[dataFrame1["Birim Fiyat"] > 100]
pahali_urunler

        Tarih   Ürün Kategori  Adet  Birim Fiyat  Toplam Tutar
2  02.08.2026  Kahve   İçecek   2.0          180         360.0

In [75]:
dataFrame1.to_excel("market_analiz_sonuclari.xlsx", index=False)

In [78]:
df_sonuc=pd.read_excel("market_analiz_sonuclari.xlsx")
df_sonuc

        Tarih   Ürün Kategori  Adet  Birim Fiyat  Toplam Tutar
0  01.08.2026    Süt   İçecek     3           45           135
1  01.08.2026  Ekmek    Fırın     8           15           120
2  02.08.2026  Kahve   İçecek     2          180           360